### ISSUE TITLE
Is it possible to create categories?

### ISSUE THREAD

**Issue by danielpuglisi** [ennova/postmarkdown#12]
Example:

```

---
title: Bar
author: Mister Foo 
category: Foobar
----
```

And show only one particular category on a certain view?

**Comment by jasoncodes** [comment]
There is currently no support for categories or tags in Postmarkdown.

**Comment by rrmartins** [comment]
@jasoncodes the pull-request number #16 has this creation of categories.

@danielpuglisi while the @jasoncodes not accept the pull-reques #16, you can used in my repo https://github.com/rrmartins/postmarkdown... :smile:

**Comment by sassydumplings** [comment]
Are you open to accepting a PR for creation of categories?

**Comment by jasoncodes** [comment]
Postmarkdown is no longer actively maintained. I’m going to close this issue.
