### ISSUE TITLE
Error when rendering posts index

### ISSUE THREAD

**Issue by LandonSchropp** [ennova/postmarkdown#15]
When I try to render my index page, I get this error message:

undefined method `captures' for nil:NilClass

The offending piece of code is in my index.html.haml file:

``` ruby
- if collection.present?
  = render collection, :summary => true
- else
  No posts found.
```

The offending line of code is the frist one. Any ideas?

**Comment by jasoncodes** [comment]
It seems that one or more of your files in `app/posts/` does not conform to the [filename format](https://github.com/ennova/postmarkdown/blob/1f6e617bb5ad75d2178d532018a70e35fbcfdebb/app/models/post.rb#L12-L17) required by Postmarkdown. Please refer to [the examples](https://github.com/ennova/postmarkdown#example-directory-structure) in our readme.

We’ll leave this issue open as we should probably have a better error message for this.

**Comment by LandonSchropp** [comment]
Yep! You were right.
