### ISSUE TITLE
Add format xml to posts_feed_path

### ISSUE THREAD

**Issue by l4u** [ennova/postmarkdown#18]
Tested under Rails 4.0

posts_feed_path does not have .xml extension
/blog/feed will result in a missing template, because the default format is :html

Adding the .xml extension /blog/feed.xml will work.
We can use `posts_feed_path(format: :xml)` in  app/views/_feed_link.html.haml 

Or do you prefer adding xml format as the default format for /blog/feed ?

**Comment by jasoncodes** [comment]
I’d definitely prefer to see the path remain as `/blog/feed`. I notice the `posts_feed` route already has `:format => :xml`.

**Comment by l4u** [comment]
In my case, `/blog/feed` returns missing template.

If it's changed to `, :defaults => {:format => :xml}` instead of  `{:format => :xml}` in `lib/postmarkdown/routes.rb`
both `/blog/feed.xml` and `/blog/feed` would work.

**Comment by jasoncodes** [comment]
Yup. Looks like we should be using the `:defaults` option.
