### ISSUE TITLE
Proposal: Make the pagination gem configurable

### ISSUE THREAD

**Issue by mkdynamic** [ennova/postmarkdown#21]
Using `kaminari` was not feasible for my specific case, since it was causing conflicts with `will_paginate` which is being used elsewhere.

Fwiw. here's the (minimal) changes to use `will_paginate`:
https://github.com/mkdynamic/postmarkdown/commit/10d6d032056c2e70b91cfec78a45f3c55294fb46

Would you be amenable to the idea of making the pagination library pluggable somehow? Someway to configure which library to use?

If this sounds like something you would merge, I can do it. Let me know your thoughts.

**Comment by jasoncodes** [comment]
It looks like amatsuda/kaminari@3cf929f7d000997ceca8a25cbfa81e5bb299088e via amatsuda/kaminari#162 should allow both kaminari and will_paginate to co-exist. Would definitely accept a patch which makes Postmarkdown use `Kaminari.config.page_method_name`. This would let Postmarkdown’s pagination to continue to work out of the box without configuration and allow both gems to co-exist with minimal configuration in the app. What are your thoughts on this?

I guess the other option (which is what you’re suggesting?) is to remove kaminari from the dependencies and require either will_paginate or kaminari to be added to an app’s Gemfile for pagination to work. My main issue with this would be that to have full coverage, Postmarkdown would need test environments for no pagination, kaminari, and will_paginate.

**Comment by kjeremy** [comment]
page_method_name doesn't quite fix the problem.  page_entries_info also presents a problem.

**Comment by jasoncodes** [comment]
Okay. That sucks. It doesn’t look like there’s any easy way to get both `page_entries_info` methods to co-exist.

Adding support for both gems with no default in the gemspec sounds like the way to go then. A brief note in the installation section of the readme should suffice.

As for testing, I am now thinking the integration test for pagination could be expanded to test with no pagination gems loaded, then test with will_paginate loaded, then test with kaminari loaded. The behaviour change should be testable by looking at the view (perhaps the pagination markup).

What do you think?

**Comment by sassydumplings** [comment]
Is this still an active issue?

**Comment by jasoncodes** [comment]
Postmarkdown is no longer actively maintained. I’m going to close this issue.
