### ISSUE TITLE
Overridden stylesheets

### ISSUE THREAD

**Issue by Tamachan87** [ennova/postmarkdown#3]
If you use the <code>rails generate postmarkdown:override --all</code> command, the created postmarkdown stylesheet in app/assets/stylesheets will be prioritised for your entire Rails app. I'm new at this, but I would just like to point this out. It might be obvious to some, but not newbies.

**Comment by twe4ked** [comment]
The generated files should show up in `git diff`. Hopefully this is clear enough. If you have any suggestions on how we could make it clearer, please let us know.
